#!/bin/bash

# Box class - new dispatcher implementation

. bashDispatcher

# ============================================================================
# Box Class Descriptor
# ============================================================================

__bashClass_registry["Box"]="|type=class|id=Box|parent=bashClass|methods=calc,area,top,end,side,bottom,volume,new|properties=length,width,height,unit,color"

# ============================================================================
# Box Implementation Functions
# ============================================================================

# Generic multiplication calculator
__Box.calc() {
  local -I self class
  local -i tot=1 required="${required:-0}"

  if ((required)); then
    (( required == $# )) || __bashClass.crash "$FUNCNAME requires $required INTEGER arguments to multiply"
  fi

  for arg in "$@"; do
    [[ "${arg:-}" =~ ^[0-9]+$ ]] || __bashClass.crash "$FUNCNAME arguments must be integers: $*"
    (( tot *= arg ))
  done

  __bashClass_RETURN="$tot"
}

# Calculate area (2D)
__Box.area() {
  local -I self class
  required=2 __Box.calc "$@"
}

# Calculate top face area
__Box.top() {
  local -I self class
  local length width
  __bashClass.parse "$self" "length" length
  __bashClass.parse "$self" "width" width
  self="$self" class="$class" __bashClass.dispatch area "$length" "$width"
}

# Calculate end face area
__Box.end() {
  local -I self class
  local height width
  __bashClass.parse "$self" "height" height
  __bashClass.parse "$self" "width" width
  self="$self" class="$class" __bashClass.dispatch area "$height" "$width"
}

# Calculate side face area
__Box.side() {
  local -I self class
  local height length
  __bashClass.parse "$self" "height" height
  __bashClass.parse "$self" "length" length
  self="$self" class="$class" __bashClass.dispatch area "$height" "$length"
}

# Calculate bottom face area (same as top)
__Box.bottom() {
  local -I self class
  self="$self" class="$class" __bashClass.dispatch top
}

# Calculate volume (3D)
__Box.volume() {
  local -I self class
  local length height width
  __bashClass.parse "$self" "length" length
  __bashClass.parse "$self" "height" height
  __bashClass.parse "$self" "width" width
  required=3 __Box.calc "$length" "$height" "$width"
}

# Box constructor - delegates to base, adds defaults
__Box.new() {
  local -I class
  : "${class:=Box}"
  __bashClass.new "$@"
}

# ============================================================================
# Register Methods
# ============================================================================

__bashClass.registerMethod Box calc __Box.calc
__bashClass.registerMethod Box area __Box.area
__bashClass.registerMethod Box top __Box.top
__bashClass.registerMethod Box end __Box.end
__bashClass.registerMethod Box side __Box.side
__bashClass.registerMethod Box bottom __Box.bottom
__bashClass.registerMethod Box volume __Box.volume
__bashClass.registerMethod Box new __Box.new
