#!/usr/bin/env bash
. boop                                         # load the framework

Counter.increment() {
  local _Class="${_Class:-Counter}" _Self="${_Self:-}"  # boilerplate — capture dispatch context
  local __Counter_increment_val                # triple-prefix naming avoids nameref collisions
  into=__Counter_increment_val $_Self.count    # read via autogenerated accessor
  (( ++__Counter_increment_val ))              # prefix form: result is always nonzero, safe under set -e
  $_Self.count "$__Counter_increment_val"      # write back via accessor (one arg = setter)
}

boopClass Counter 'has:count public:increment'

into=a Counter count=0 && echo "a=$a"
into=b Counter count=0 && echo "b=$b"
o=( "$a" "$b" ) # object names into an array

$a.increment                                     # a.count = 1
for i in loop three times; do $b.increment; done # b.count = 3

for obj in "${o[@]}"; do _EOL=" hits for $obj"$'\n' $obj.count; done
